//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    
    
    using System;
    using System.Collections.Generic;
    
    public partial class GetInvoiceByIDView
    {
        public int InvoiceID { get; set; }
        public int InvoiceNumber { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public string ReferenceInvoice { get; set; }
        public System.DateTime ExpirationInvoiceDate { get; set; }
        public Nullable<double> InvoiceDisCount { get; set; }
        public int InvoiceDetailQuantity { get; set; }
        public decimal InvoiceDetailUnitPrice { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string TaxDescription { get; set; }
        public Nullable<decimal> TaxValue { get; set; }
        public string TypeOfPayDescription { get; set; }
        public string BodegaAddress { get; set; }
        public string BodegaName { get; set; }
        public string BodegaEmail { get; set; }
        public string BodegaIndustrialRegistration { get; set; }
        public string BodegaPhone { get; set; }
        public string CustomerAddress1 { get; set; }
        public string CustomerAddress2 { get; set; }
        public string CustomerBusinessRegistration { get; set; }
        public string CustomerCellPhone { get; set; }
        public string CustomerCompanyName { get; set; }
        public string CustomerContactName { get; set; }
        public string CustomerCustomerCode { get; set; }
        public string CustomerDocumentID { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone1 { get; set; }
        public string CustomerTaxRegistration { get; set; }
        public string EmployeeDocumentIdentity { get; set; }
        public string EmployeeFullName { get; set; }
        public string MunicipalityOfCustomer { get; set; }
        public string ProvinceOfCustomer { get; set; }
    }
}
