//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    
    
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int InvoiceDetailsID { get; set; }
        public int InvoiceID { get; set; }
        public int ProductDetailID { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public int KardexID { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<double> Discount { get; set; }
    
        public virtual Kardex Kardex { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
