//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    
    
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.PaidAccounts = new HashSet<PaidAccount>();
        }
    
        public int InvoiceID { get; set; }
        public int InvoiceNumber { get; set; }
        public int CustomerID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int BodegaID { get; set; }
        public int TypeOfPayID { get; set; }
        public Nullable<int> TaxID { get; set; }
        public Nullable<double> DisCount { get; set; }
        public string ReferenceInvoice { get; set; }
        public System.DateTime ExpirationInvoiceDate { get; set; }
        public string Comments { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        public virtual Tax Tax { get; set; }
        public virtual TypeOfPay TypeOfPay { get; set; }
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaidAccount> PaidAccounts { get; set; }
    }
}
