//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    
    
    using System;
    using System.Collections.Generic;
    
    public partial class Kardex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kardex()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int KardexID { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string TypeOfMove { get; set; }
        public Nullable<double> KardexIn { get; set; }
        public Nullable<double> KardexOut { get; set; }
        public double KardexStock { get; set; }
        public Nullable<double> LastCost { get; set; }
        public Nullable<double> AverageCost { get; set; }
        public int ProductDetailsID { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
