//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    
    
    using System;
    using System.Collections.Generic;
    
    public partial class PaidAccountDetail
    {
        public int PaidAccountDetailID { get; set; }
        public int PaidAccountID { get; set; }
        public string Concept { get; set; }
        public decimal Payment { get; set; }
        public System.DateTime DatePayment { get; set; }
        public string RefNumberInvoicePay { get; set; }
    
        public virtual PaidAccount PaidAccount { get; set; }
    }
}
