//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    
    
    using System;
    using System.Collections.Generic;
    
    public partial class PaidAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaidAccount()
        {
            this.PaidAccountDetails = new HashSet<PaidAccountDetail>();
        }
    
        public int PaidAccountID { get; set; }
        public int InvoiceID { get; set; }
        public System.DateTime DateEmit { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public decimal Amount { get; set; }
        public int DayDelay { get; set; }
        public string State { get; set; }
        public decimal AmountPending { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaidAccountDetail> PaidAccountDetails { get; set; }
    }
}
