//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    
    
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDetail()
        {
            this.Kardexes = new HashSet<Kardex>();
        }
    
        public int ProductDetailsID { get; set; }
        public int ProductID { get; set; }
        public Nullable<decimal> UnitPrice1 { get; set; }
        public Nullable<decimal> UnitPrice2 { get; set; }
        public Nullable<decimal> UnitPrice3 { get; set; }
        public decimal ProductCost { get; set; }
        public int BodegaID { get; set; }
        public Nullable<int> TaxID { get; set; }
        public int Stock { get; set; }
    
        public virtual Bodega Bodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kardex> Kardexes { get; set; }
        public virtual Product Product { get; set; }
        public virtual Tax Tax { get; set; }
    }
}
