//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    using System;
    
    public partial class sp_getAllProvinces
    {
        public int ProvinceID { get; set; }
        public string Name { get; set; }
    }
}
