//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    using System;
    
    public partial class Sp_GetUnits
    {
        public int UnitID { get; set; }
        public string UnitDescription { get; set; }
    }
}
