//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    using System;
    
    public partial class Sp_GetAllBodega
    {
        public int BodegaID { get; set; }
        public string BodegaName { get; set; }
        public string BodegaAddress { get; set; }
        public string Phone { get; set; }
        public string IndustrialRegistration { get; set; }
        public string Email { get; set; }
    }
}
