//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    using System;
    
    public partial class Sp_GetAllInvoicesDetailsOverDue
    {
        public int InvoiceNumber { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime DateEmit { get; set; }
        public decimal Amount { get; set; }
        public decimal AmountPending { get; set; }
        public int DayDelay { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> LastPayment { get; set; }
    }
}
