//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Koontabi.Domain
{
    using System;
    
    public partial class Sp_GetProductByID
    {
        public int ProductID { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Description { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<double> KardexIn { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public Nullable<decimal> UnitPrice1 { get; set; }
        public Nullable<decimal> UnitPrice2 { get; set; }
        public Nullable<decimal> UnitPrice3 { get; set; }
        public int Stock { get; set; }
        public Nullable<int> InvoiceWithPrice { get; set; }
        public bool InvoiceWithoutStock { get; set; }
        public bool State { get; set; }
        public Nullable<int> TaxID { get; set; }
        public int KardexID { get; set; }
        public int ProductDetailsID { get; set; }
        public int BodegaID { get; set; }
    }
}
